export { inventoryRouter } from "./inventory/inventory.routes.js"
export { npcRouter } from "./npcs/npc.routes.js"
export { objectRouter } from "./objects/objects.routes.js"
export { pcRouter } from "./pc/pc.routes.js"
export { userRouter } from "./users/user.routes.js"